apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: angular
          image: goksatexpleo/javacoffeshop:30
          ports:
            - containerPort: 8083
    restartPolicy: Always
