apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: angular
          image: goksatexpleo/javacoffeshop:1
          ports:
            - containerPort: 80
    restartPolicy: Always
